// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: golfers.sql

package database

import (
	"context"
)

const createGolfer = `-- name: CreateGolfer :one
INSERT INTO golfers (id, created_at, updated_at, email_address, username, hashed_password)
VALUES (gen_random_uuid (), NOW(), NOW(), $1, $2, $3)
RETURNING id, created_at, updated_at, email_address, username, hashed_password
`

type CreateGolferParams struct {
	EmailAddress   string
	Username       string
	HashedPassword string
}

func (q *Queries) CreateGolfer(ctx context.Context, arg CreateGolferParams) (Golfer, error) {
	row := q.db.QueryRowContext(ctx, createGolfer, arg.EmailAddress, arg.Username, arg.HashedPassword)
	var i Golfer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailAddress,
		&i.Username,
		&i.HashedPassword,
	)
	return i, err
}

const retrieveGolferByUsername = `-- name: RetrieveGolferByUsername :one
SELECT id, created_at, updated_at, email_address, username, hashed_password from golfers
WHERE username = $1
`

func (q *Queries) RetrieveGolferByUsername(ctx context.Context, username string) (Golfer, error) {
	row := q.db.QueryRowContext(ctx, retrieveGolferByUsername, username)
	var i Golfer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailAddress,
		&i.Username,
		&i.HashedPassword,
	)
	return i, err
}
