name: Go build and test

on:
  pull_request:
    branches:
      - dev
      - main

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./src/go.mod

      - name: Build
        run: |
        - cd src
        - go build -v 

      - name: Test
        run: |
        - cd src
        - go test -v